### ISSUE TITLE
Continue to tag releases

### ISSUE THREAD

**Issue by worldofpeace** [florisla/stm32loader#27]
It appears there isn't a `v5.0.0` tag in this repository for the latest release.
Can you please continue to tag your releases this way?
It would make packaging this software convenient for downstreams that'd like to use GitHub and it's a good practice in general.

**Comment by florisla** [comment]
Sure,
Thanks for reporting!

Tag `v0.5.0` has been added.

I'll keep this in mind for future releases -- including updating `CHANGELOG.md` which is overdue as well.

Good to know there are downstream users ;-)
