### ISSUE TITLE
Support writing / reading hex files

### ISSUE THREAD

**Issue by florisla** [florisla/stm32loader#39]
Would prevent mixups like happened in #31.

**Comment by michsens** [comment]
For this purpose I use:

```
python3 /usr/bin/hex2bin.py "$binToFlash" "$binToFlash"".bin"
```

in a shell script. It should be possible to integrate it directly into the stm32loader.

**Comment by florisla** [comment]
@michsens is that `hex2bin.py` from this project? https://python-intelhex.readthedocs.io/en/stable/

**Comment by g2pmas** [comment]
Hello.
I use this:
`arm-none-eabi-objcopy -I ihex --output-target=binary code00.hex code00.bin`

**Comment by florisla** [comment]
Support for hex files has landed in master.
