### ISSUE TITLE
Wrong masking of flash page number?

### ISSUE THREAD

**Issue by michsens** [florisla/stm32loader#44]
I think I found a little issue in the bootloader.py.

See following lines:
https://github.com/florisla/stm32loader/blob/497e1f7064129eaabd75b7a73412ac89c1f311a4/stm32loader/bootloader.py#L537-L553

There you mask `page` with 0xFF but before it is checked to be smaller then 0xFFFE (65535). Shouldn't there be the mask like 0xFFF?

With a page length of 256 you get an error message:
`struct.error: argument out of range`

A value of 257 does not interrupt the program but the flash memory is blocked for further actions. A following `read_memory` command i.e. is terminated with:
`stm32loader.bootloader.CommandError: Can't read port or timeout`

Erasing 260 pages upward throws following:
`stm32loader.bootloader.CommandError: NACK 0x44 erasing failed`

I was faced with this problem by trying to flash an STM32L010K8 controller. For more details, I open another issue report.

Regards 

Robert.

**Comment by florisla** [comment]
Included this fix in 40fb05972ef87c72c870cecd1f1bc0bc43d22ad8 .
