### ISSUE TITLE
Can't init into bootloader. Ensure that BOOT0 is enabled and reset the device.

### ISSUE THREAD

**Issue by embpic** [florisla/stm32loader#57]
Hi,
I am using STM32F103xx and i wanted to use the UART bootlaoder. I have changed the BOOT0 pin state to 1 like the one shown in below image.

![image](https://user-images.githubusercontent.com/87866976/151650386-88459d8c-245d-4a7d-86c5-7ad03f04c29f.png)

after executing following command as "**sudo python3 stm32loader -r -p /dev/ttyUSB0 -e -w -v led_blink.bin**" i am getting following errors,

```
Activating bootloader (select UART)
Bootloader activation timeout -- retrying
Can't init into bootloader. Ensure that BOOT0 is enabled and reset the device.

```

**Comment by florisla** [comment]
It looks like `BOOT0` is set correctly for an STM32F103.  You need to press the _Reset_ button on the blue STM32F1 board before starting `stm32loader`.

If that does not help, please consider:
* You can use the UART adapter's `DTR` pin to toggle `RESET` automatically.
* Check if both devices remain powered (e.g. place a LED with a resistor on a 5V or 3.3V line).
* Check if the UART adapter uses 5V or 3.3V levels, and if that is compatible with your target board.
* Re-do all wire connections.  Wires can be flaky!

**Comment by florisla** [comment]
Also, you can lower the baudrate and double-check that the UART adapter has pull-up resistors on the RX and TX lines,
