### ISSUE TITLE
Error when passing address in hex format

### ISSUE THREAD

**Issue by etrommer** [florisla/stm32loader#64]
When running the example from the Readme, an error is thrown:

```bash
> stm32loader -r -p /dev/ttyUSB1 -f WL -l 0x10000 -a 0x08000000 dump.bin
usage: stm32loader [-h] [-e] [-u] [-w] [-v] [-r] [-l LENGTH] -p PORT [-b BAUD] [-a ADDRESS] [-g ADDRESS] [-f FAMILY] [-V] [-q] [-s] [-R] [-B] [-n] [-P {even,none}] [--version] [FILE.BIN]
stm32loader: error: argument -l/--length: invalid int value: '0x10000'
```
this is because argparse expects integer arguments to be decimal, not hex.

Discussion and proposed fix:
https://stackoverflow.com/questions/25513043/python-argparse-fails-to-parse-hex-formatting-to-int-type

**Comment by florisla** [comment]
Fixed in 0.6.0
