### ISSUE TITLE
On Raspberry:   WARNING: The script stm32loader is installed in '/home/pi/.local/bin' which is not on PATH.

### ISSUE THREAD

**Issue by Tonio16** [florisla/stm32loader#66]
Hello

I think that is linked to the issue 49 but I have this warning on my pi, debian 11.

  WARNING: The script stm32loader is installed in '/home/pi/.local/bin' which is not on PATH.

I am not skilled enough to solve it...

Regards

Antoine

**Comment by florisla** [comment]
Hi, this is just a warning.

If  you want to execute `stm32loader`, you can enter this:

    /home/pi/.local/bin/stm32loader

If you want to be able to execute it by simply typing `stm32loader`, then you have to configure your shell to look for executables in the folder `/home/pi/.local/bin`.  This is called 'adding a folder to $PATH'.

Another way to start stm32loader is ask Python to find and run it:

    python3 -m stm32loader
